Importing Numpy Library


In [14]:
import numpy as np 

Matrix Addition 

two matrices can be added only if they have the same shape

In [15]:
a = np.array([[2,4],[5,6]])

b = np.array([[1,3],[4,7]])

b.shape


(2, 2)

Adding the Matrices

In [16]:
sum = a + b
sum


array([[ 3,  7],
       [ 9, 13]])

In [17]:
sum2 = np.add(a,b)
sum2

array([[ 3,  7],
       [ 9, 13]])

Substraction matrix

In [9]:

a = np.array([[2,4],[5,6]])

b = np.array([[1,3],[4,7]])

b.shape

sub = a - b
sub




array([[ 1,  1],
       [ 1, -1]])

In [18]:
sub = np.subtract(a,b)
sub


array([[ 1,  1],
       [ 1, -1]])

In [25]:
#crete two matrices with random values
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(20,size=(3,3))
mat1


array([[6, 2, 5],
       [0, 7, 1],
       [9, 0, 8]])

In [26]:
mat2
# mat


array([[17, 19, 16],
       [ 2,  8, 12],
       [12, 12, 10]])

In [28]:
mat = np.subtract(mat1,mat2)
mat

array([[-11, -17, -11],
       [ -2,  -1, -11],
       [ -3, -12,  -2]])

Multiplying a matrix by a scalar 

In [30]:
x = 5
y = np.random.randint(10,size=(4,4))

y 


array([[4, 3, 6, 6],
       [3, 4, 7, 2],
       [4, 0, 9, 0],
       [5, 6, 9, 9]])

In [31]:
product = np.multiply(x,y)
product

array([[20, 15, 30, 30],
       [15, 20, 35, 10],
       [20,  0, 45,  0],
       [25, 30, 45, 45]])

Multipling 2 matrix

In [61]:
#crete two matrices with random values
mat1 = np.random.randint(5,size=(3,3))
mat2 = np.random.randint(5,size=(3,4))



In [62]:
print(mat1)

[[0 3 1]
 [0 4 2]
 [0 4 2]]


In [63]:
mat2

array([[4, 4, 1, 4],
       [0, 3, 0, 3],
       [4, 2, 4, 0]])

In [65]:
product = np.dot(mat1,mat2)
product

array([[ 4, 11,  4,  9],
       [ 8, 16,  8, 12],
       [ 8, 16,  8, 12]])

In [36]:
product.shape

(3, 4)

In [41]:
#crete two matrices with random values
mat1 = np.random.randint(5,size=(3,3))
mat2 = np.random.randint(5,size=(4,4))


In [42]:
product = np.dot(mat1,mat2)
product

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

Element wise Matrix  Multiplication

In [51]:
#crete two matrices with random values
mat1 = np.random.randint(5,size=(3,3))
mat2 = np.random.randint(5,size=(3,3))

In [52]:
print(mat1)

[[0 3 0]
 [0 2 3]
 [4 2 3]]


In [53]:
print(mat2)

[[4 3 4]
 [4 2 3]
 [4 0 3]]


In [54]:
product = np.multiply(mat1,mat2)
product

array([[ 0,  9,  0],
       [ 0,  4,  9],
       [16,  0,  9]])