In [2]:
import numpy as np


Crating a matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2 = np.array([[12,23,5],[3,63,74],[4,6,23]])
matrix_2


array([[12, 23,  5],
       [ 3, 63, 74],
       [ 4,  6, 23]])

In [7]:
matrix_2.shape

(3, 3)

Creating Matices with Random values

In [9]:
random_mat = np.random.rand(3,3)
print(random_mat)

[[0.90755908 0.11516689 0.0166932 ]
 [0.38776221 0.48893258 0.64141614]
 [0.89911722 0.54807518 0.24992843]]


In [10]:
#creating matrix with random integers
random_integer_mat = np.random.randint(100,size=(4,5))
random_integer_mat

array([[ 9, 36, 78, 62, 19],
       [36, 42, 46,  7, 28],
       [18, 72, 55, 31, 23],
       [92, 28, 86, 23, 77]])


Matrix with all the values as 1

In [11]:
matrix_3 = np.ones((2,3))
matrix_3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
matrix_3 = np.ones((2,3),dtype=int)
matrix_3

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:

matrix_3 = np.ones((5,5),dtype=int)
matrix_3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Null Matrix or zero matrix

In [14]:
null_matrix = np.zeros((4,4))
null_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Identity matrix 

In [15]:
identity_mat = np.eye(5,5)
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Transpose of a matrix

In [16]:
#matrix with random integet values 
a = np.random.randint(100,size =(4,5))

a

array([[83, 14, 32, 44, 37],
       [52, 40, 15, 95, 42],
       [48, 99, 63, 89, 85],
       [86, 51, 28, 22, 58]])

In [19]:
transpose_of_a = np.transpose(a)

transpose_of_a

array([[83, 52, 48, 86],
       [14, 40, 99, 51],
       [32, 15, 63, 28],
       [44, 95, 89, 22],
       [37, 42, 85, 58]])