<a href="https://colab.research.google.com/github/Amankumar10/AI_practice_colab/blob/main/Complete_Machine_Learning_Course_in_60_Hours_Part_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy-Numberical Python


Advantage of Numpy Arrays:


1.Allows several Mathematical Operations

2.Faster operations


In [ ]:
import numpy as np


List vs numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)


0.0009207769999997062


In [ ]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0012046950000002


Numpy Arrays

In [ ]:
#List
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1 dim array
a =np_array = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
#create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of one
y= np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#crete a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.57773854 0.86918398 0.72723635 0.86591461]
 [0.42180363 0.02826171 0.59705326 0.73264628]
 [0.05411581 0.8087476  0.95314176 0.1772586 ]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[91 16 59 56 86]
 [33 75 29 15 68]
 [31 18 27 28 66]]


In [ ]:
#array of evenly spaced values --> specifying the no. of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array


In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[24 81 63 34 30]
 [80 24 75 73 58]
 [24 74 27 52 12]
 [20 61 38 83 17]
 [73 34 18 60 14]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elementss in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


**Mathematical operations on a np array**

In [ ]:
list1 = [1,1,4,5,5]
list2 = [5,4,67,6]

print(list1 + list2)

[1, 1, 4, 5, 5, 5, 4, 67, 6]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[8 5 5]
 [0 1 1]
 [5 9 4]]
[[14 12 13]
 [12 15 12]
 [16 16 11]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 17 18]
 [12 16 13]
 [21 25 15]]
[[ -6  -7  -8]
 [-12 -14 -11]
 [-11  -7  -7]]
[[112  60  65]
 [  0  15  12]
 [ 80 144  44]]
[[0.57142857 0.41666667 0.38461538]
 [0.         0.06666667 0.08333333]
 [0.3125     0.5625     0.36363636]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[9 0 2]
 [9 4 3]
 [5 2 1]]
[[14 13 16]
 [17 11 11]
 [10 15 10]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 13 18]
 [26 15 14]
 [15 17 11]]
[[ -5 -13 -14]
 [ -8  -7  -8]
 [ -5 -13  -9]]
[[126   0  32]
 [153  44  33]
 [ 50  30  10]]
[[0.64285714 0.         0.125     ]
 [0.52941176 0.36363636 0.27272727]
 [0.5        0.13333333 0.1       ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[0 8 0]
 [4 4 7]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 4]
 [8 4]
 [0 7]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 4]
 [8 4]
 [0 7]]
(3, 2)


In [ ]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 4 4]
 [4 9 2]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)